<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Accounting Energy Report</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 11px;
            color: #333;
            margin: 0;
            padding: 0;
        }
        .header {
            border-bottom: 2px solid #2e7d32;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #2e7d32;
            margin: 0;
            font-size: 22px;
            text-transform: uppercase;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #666;
            font-size: 10px;
        }
        .info-table {
            width: 100%;
            margin-bottom: 25px;
        }
        .info-table td {
            padding: 3px 0;
        }
        .label {
            font-weight: bold;
            color: #555;
            width: 110px;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        table.data-table th {
            background-color: #f1f8e9;
            color: #2e7d32;
            padding: 10px 8px;
            text-align: left;
            text-transform: uppercase;
            font-size: 10px;
            border-bottom: 2px solid #2e7d32;
        }
        table.data-table td {
            padding: 10px 8px;
            border-bottom: 1px solid #eee;
        }
        .text-right {
            text-align: right;
        }
        .font-bold {
            font-weight: bold;
        }
        .summary-section {
            margin-top: 30px;
            page-break-inside: avoid;
        }
        .summary-card {
            background-color: #f1f8e9;
            border: 1px solid #c5e1a5;
            padding: 20px;
            border-radius: 4px;
            text-align: right;
        }
        .total-amount {
            font-size: 24px;
            font-weight: 900;
            color: #2e7d32;
            display: block;
            margin-top: 5px;
        }
        .footer {
            position: fixed;
            bottom: -20px;
            left: 0;
            right: 0;
            height: 20px;
            font-size: 9px;
            text-align: center;
            color: #aaa;
            border-top: 1px solid #eee;
            padding-top: 5px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Accounting Energy Report</h1>
        <p>Industrial Finance & Energy Management System</p>
    </div>

    <table class="info-table">
        <tr>
            <td class="label">Billing Period:</td>
            <td>{{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}</td>
            <td class="label" style="text-align: right">Generated At:</td>
            <td style="text-align: right">{{ now()->format('d M Y H:i') }}</td>
        </tr>
        <tr>
            <td class="label">Target Entity:</td>
            <td>{{ $deviceName }}</td>
            <td class="label" style="text-align: right">Currency:</td>
            <td style="text-align: right">IDR (Indonesian Rupiah)</td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Device Name</th>
                <th class="text-right">Usage (kWh)</th>
                <th class="text-right">Amount (IDR)</th>
            </tr>
        </thead>
        <tbody>
            @php $totalKwh = 0; @endphp
            @foreach($reports as $row)
                @php $totalKwh += $row->kwh_usage; @endphp
                <tr>
                    <td class="font-bold">{{ \Carbon\Carbon::parse($row->recorded_date)->format('d/m/Y') }}</td>
                    <td>{{ $row->device->name }}</td>
                    <td class="text-right">{{ number_format($row->kwh_usage, 2) }}</td>
                    <td class="text-right font-bold">Rp {{ number_format($row->energy_cost, 0) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary-section">
        <div class="summary-card">
            <span class="label">GRAND TOTAL ENERGY COST</span>
            <span class="total-amount">Rp {{ number_format($totalCost, 0) }}</span>
            <p style="margin: 5px 0 0 0; color: #666; font-size: 9px;">Total Consumption: {{ number_format($totalKwh, 2) }} kWh</p>
        </div>
    </div>

    <div class="footer">
        Generated by Energy-Tracker Finance Module • Confidential Report
    </div>
</body>
</html>
